### ISSUE TITLE
Latest version  throw's errror

### ISSUE THREAD

**Issue by addy3494** [K4rakara/freshfetch#18] opened 2021-02-07 18:37 UTC
When compiled from source runs fine, aur package throws error, release version 0.1.2 shows as 0.0.1

![error](https://user-images.githubusercontent.com/22428691/107155926-531d1c80-69a1-11eb-82de-10b02c14d10c.png)

❯ ./freshfetch --version
freshfetch 0.0.1

**Comment by K4rakara** [comment] 2021-02-25 03:51
Duplicate of #17 -- Something went wrong while I was packaging `freshfetch-bin`. `freshfetch-git` should work fine. I'll be repackaging it for 0.2.0

**Comment by K4rakara** [comment] 2021-04-17 00:44
Should be fixed with 0.2.0

**Closed by K4rakara** 2021-04-17 00:44 UTC
